### ISSUE TITLE
Don't work, just load more feeds

### ISSUE THREAD

**Issue by githu1511** [openbin/smartnews#2]
Hi,

The extension don't sort the feeds. When I click on "Sort by likes", It starts loading more feeds, and that's all.

I tried to modify the value of "Max feeds to sort" box, but the problem remains same.
I tried to sort less feeds too.

Thanks.

**Comment by openbin** [comment]
Can you tell me which feed would it not work on ? I've tried with a few & it works as mentioned. If the number in the box next to the sort button is too high, it'll first load all those feeds before sorting. You can reduce that and give it a try. 

For any additional functionality, pull requests are welcome.
